ansible_user: ec2-user
ansible_password: DevOps321
MONGODB_HOST: mongodb-"{{ env }}".dive2devops.com
CATALOGUE_HOST: catalogue-"{{ env }}".dive2devops.com
REDIS_HOST: redis-"{{ env }}".dive2devops.com
USER_HOST: user-"{{ env }}".dive2devops.com
CART_HOST: cart-"{{ env }}".dive2devops.com
MYSQL_HOST: mysql-"{{ env }}".dive2devops.com
SHIPPING_HOST: shipping-"{{ env }}".dive2devops.com
RABBITMQ_HOST: rabbitmq-"{{ env }}".dive2devops.com
PAYMENT_HOST: payment-"{{ env }}".dive2devops.com